name: Context Example

on: [push]

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "Set Environment Variable"
        env:
          MY_ACTION: ${{ github.action }}
          MY_ACTOR: ${{ github.actor }}
        run: |
          echo "Action! $MY_ACTION"
          echo "Actor! $MY_ACTION"
