name: Context Example

on: [push]

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "Set Environment Variable"
        env:
          MY_ACTION: ${{ github.action }}
        run: echo "Hello! $MY_ACTION"
