on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: msebton-captech/barsoom
        with:
          name: 'Brown'
      # Use the output from the `hello` step
      - name: Get the output
        run: echo "The time was ${{ steps.hello.outputs.greeting }}"
