name: "Webhook Event example"

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  respond-to-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          echo "GITHUB_EVENT_NAME=${{ github.event_name }}" >> $GITHUB_ENV

      - name: Run a script
        run: |
          echo "Event of type: $GITHUB_EVENT_NAME"
